### ISSUE TITLE
gui improvements required

### ISSUE THREAD

**Issue by davidkao41** [180D-FW-2021/Team5#19]
1. game end - need popup to input user name
2. info - score, powerups, turns, survived time (game time), current datetime
turns - not super required, but could be fun - needs data from imu
datetime - already implemented in leaderboard
3. turn into json and make http post
in derrick/website/Team5/website/backend/tester.py

**Comment by derrickkhuynh** [comment]
#25 

last 2 commits of this are what's important.

**Comment by davidkao41** [comment]
commited everything besides the turns

**Comment by davidkao41** [comment]
ADDED TURNS
